name: Build slim packages

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    
    strategy:
      matrix:
        erl_otp:
        - erl23.2.2
        os:
        - ubuntu20.04
        - centos8

    container: emqx/build-env:${{ matrix.erl_otp }}-${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v1
    - name: build packages
      run: make emqx-pkg
    - name: pakcages test
      run: |
        export CODE_PATH=$GITHUB_WORKSPACE
        .ci/build_packages/tests.sh
